language: php

matrix:
    include:
     - php: 5.3
     - php: 5.4
     - php: 5.5
     - php: 5.6
     - php: 7.0
     - php: hhvm
     - php: nightly
    allow_failures:
     - php: hhvm
     - php: nightly
    fast_finish: true

notifications:
  email: false

before_script:
 - composer install --prefer-dist

script:
 - vendor/bin/phpspec run --format pretty
